# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2343c4b92bf1a05746a49f808e960c45fa1919f1ad17d1b500e1b0c7be6a61a92d54d2425d444f577f3c78eca1d84f5ab31332b8bed680827db0e74561ddec1b

test:
  secret_key_base: 9edfae76b44bbebbcae6b462bcd7e91d02b938d988bb3998da103ded6fce64805ab7e1905b85c7de8087d19f35cee57e6ca2f8b220da4074d80e42e9bcae85b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
