# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c790eb74bdc97aec655f6cbbbbd6d8ec59b5331cfa03415d9fe966b78dbdb5e86dea6bef1cd374d0e963e318db0bdab5c0e0a44875804752cd1908320b740fae

test:
  secret_key_base: 691f9bdb74f11c287d76857de27e9b35bba9e0855fa214fb9af62747b4fa1d615df794c8efc75eaa926109e3f5ef34c0a520883cbb1eba6181d8c8de20ec5c40

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
