# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a823635f1e5a48409dd04d7cd22028596d8ae1c24796b91dc5411ab2d4815a8329c90c62439fe0efd3ad596fcbb60620e08a751311be44a70467c8dbaf10b9ad

test:
  secret_key_base: 0a6003362bf587feb2a0d8601dc23b271de7d79dce0d18e73e7e88d966726c78c4857e0606d58ec7dffcad0d5ece6fedfbe3296430387111b2ff5f5441c43416

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
